---
name: test

"on":
  pull_request: {}
  push:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ["7.4", "8.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v2
      - id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Test
        run: |
          composer install
          ./vendor/bin/phing
